version: '3.7'
services:
  php-fpm70:
    image: tunichan
    volumes:
#      - tunichan/php/php-fpm.conf:/etc/opt/rh/rh-php70/php-fpm.conf
#      - tunichan/php/php.ini
#      - tunichan/php/php-fpm.d/www.conf
       - tunichan:/var/www/html
    networks:
      - tunichan-internal
      
  web:
    image: nginx
    command: /bin/bash -c "exec nginx -g 'daemon off;'"
    ports:
      - "81:80"
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/tunichan.conf  
    volumes:
      - tunichan:/var/www/html
#      - tunichan/tunichan.conf:/etc/nginx/conf.d/tunichan.conf 
    environment:
      - NGINX_HOST=tunichan.hentai.agency
      - NGINX_PORT=80
    networks:
      - webgateway
      - tunichan-internal
    labels:
      - traefik.port=80
      - traefik.docker.network=webgateway
      - traefik.frontend.rule=Host:tunichan.hentai.agency
      - traefik.frontend.priority=50
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8g4hF4g5484g5h
      MYSQL_DATABASE: tunichan
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - tunichan-internal
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=db
    restart: always
    labels:
     - traefik.port=80
     - traefik.docker.network=webgateway
     - traefik.frontend.rule=Host:phpmyadmin.hentai.agency
     - traefik.frontend.priority=50 
    volumes:
     - /sessions 
    networks:
     - webgateway
     - tunichan-internal
     
networks:
  webgateway:
    external: true
  tunichan-internal:
    internal: true
volumes:
  mysql:
    external: true
  tunichan:
    external: true
configs:
  nginx:
    external: true
